---
- name: debug
  debug:
    msg: "jeste resolvem"

- name: find app
  set_fact:
    _reg_dns: "{{ groups['all']|
                  map('extract', hostvars, ['apps', app.value.resolv.addresses.from_app])|
                  zip(groups['all'])|
                  selectattr(0,'defined')|
                  list }}"

- name: get ips
  set_fact:
    _reg_dns_ips: "{{ _reg_dns|
                      map('select','string')|
                      map('list')|
                      flatten|
                      map('extract', hostvars,'ansible_host')|
                      list }}"
- name: debug
  debug:
    msg: "{{ _reg_dns_ips }}"
  run_once: true

- block:
    - name: copy resolv.conf
      template:
        src: resolv.conf
        dest: /etc/resolv.conf
        mode: 0644

    - name: disable resolv updates by network manager
      ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        section: main
        option: dns
        value: none
        mode: 0644
      when: ansible_distribution_major_version == "8"

    - name: disable resolv updates by network scripts
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        line: "PEERDNS=no"
        regexp: "^PEERDNS="
      when: ansible_distribution_major_version == "7"

  become: true
  become_user: root
